services:
  db:
    image: postgres:latest
    container_name: technical_support_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - technical_support_pgdata:/var/lib/postgresql/data/pgdata
    restart: always
    env_file:
      - .env

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}?sslmode=disable"
    ports:
      - "${POSTGRES_EXPORTER_PORT}:9187"

  redis:
      image: redis:latest
      container_name: technical_support_redis
      command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - technical_support_redis_data:/data
      restart: always

  redis-exporter:
    image: oliver006/redis_exporter
    environment:
        REDIS_ADDR: redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}
    ports:
      - "${REDIS_EXPORTER_PORT}:9121"
    depends_on:
      - redis

volumes:
  technical_support_pgdata:
  technical_support_redis_data:
