{
 "title": "HTTP",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Error rate %",
   "type": "stat",
   "description": "Оценка доли ошибок среди всех запросов.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "100 * $A / $B", "type": "math" }
   ]
  },
  {
   "title": "Error rate by status",
   "type": "timeseries",
   "description": "Показывает, какие ошибки (4xx или 5xx) чаще встречаются.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by(status) (rate(app_http_requests_total{status=~\"4..|5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average request duration (5m rate)",
   "type": "timeseries",
   "description": "Средняя длительность HTTP-запросов по маршрутам (5 минут)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "timeseries",
   "description": "Показывает задержку (latency) для 95% запросов.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route) (rate(app_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP RPS per Route",
   "type": "timeseries",
   "description": "Показывает нагрузку на каждый маршрут — сколько запросов приходит каждую секунду.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(route) (rate(app_http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by route/status",
   "type": "table",
   "description": "Табличный обзор всех маршрутов с методами и статусами, включая RPS.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(method, route, status) (rate(app_http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}