global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
